@tool
class_name ASTNode extends RefCounted

var type = ''
var name = ''
var parent = null
var isRoot = false
var gmui:GMUI = null
var rgmui:GMUI = null
var childRgmuis:Array[GMUI] = []
var props:Array[Prop] = []
var slotName:String = ''
var sceneXmlPath:String = ''
var sceneNode:ASTNode = null
var sceneRoot:ASTNode = null
var forTempDict:Dictionary = {}
var properties:Dictionary = {}
var bindDict:Dictionary = {}
var parentScene:ASTNode = null
var templateInfo:TemplateInfo = null
var template:ASTNode = null
var hasFor:bool = false
var forFlag:bool = false
var forValue:ForValue = null
var models:Array[Model] = []
var model:Model = null
var refName:String = ''
var ifValue:IfValue = null
var index:int = -1
var children:Array[ASTNode] = []
